# Kenya counties and constituencies data
KENYA_LOCATIONS = {
    "Nairobi": ["Westlands", "Central", "Dagoretti North", "Dagoretti South", "Kasarani", "Ruaraka", "Embakasi East", "Embakasi Central", "Embakasi South", "Embakasi North", "Embakasi West", "Makadara", "Kamukunji", "Starehe"],
    "Mombasa": ["Mvita", "Changamwe", "Kisauni", "Likoni", "Nyali"],
    "Kisumu": ["Kisumu Town", "Kisumu East", "Kisumu West", "Nyakach", "Muhoroni", "Seme"],
    "Nakuru": ["Nakuru Town", "Naivasha", "Njoro", "Gilgil", "Kuresoi North", "Kuresoi South", "Rongai"],
    "Machakos": ["Machakos Town", "Athi River", "Kangundo", "Matungulu", "Mwala", "Yatta"],
    "Kilifi": ["Kilifi Town", "Malindi", "Lamu", "Tanariver"],
    "Laikipia": ["Laikipia East", "Laikipia West", "Laikipia North"],
    "Narok": ["Narok Town", "Narok East", "Narok West", "Narok South", "Trans Mara"],
    "Kajiado": ["Kajiado Central", "Kajiado East", "Kajiado North", "Kajiado South", "Kajiado West"],
    "Uasin Gishu": ["Eldoret", "Turbo", "Kesses", "Soy", "Ainabkoi"],
    "Kakamega": ["Kakamega", "Lurambi", "Mumias", "Navakholo", "Shinyalu", "Ikolomani", "Butere"],
    "Bungoma": ["Bungoma Town", "Webuye East", "Webuye West", "Kabuchai", "Kimilili", "Kanduyi", "Sirisia", "Mt. Elgon"],
    "Trans Nzoia": ["Kitale", "Endebess", "Kiminini"],
    "Samburu": ["Samburu East", "Samburu Central", "Samburu North"],
    "Baringo": ["Baringo Central", "Baringo North", "Baringo South", "Tiaty", "Elgeyo/Marakwet"],
    "Elgeyo Marakwet": ["Iten", "Keiyo", "Marakwet West", "Marakwet East"],
    "Nandi": ["Nandi Hills", "Aldai", "Nandi South", "Nandi Central", "Nandi East"],
    "Kericho": ["Kericho", "Ainamoi", "Belgaum", "Bureti", "Sigowet"],
    "Bomet": ["Bomet", "Chepalungu", "Bomet East", "Sotik"],
    "Nyamira": ["Nyamira", "Nyamira South", "North Mugirango", "South Mugirango"],
    "Kisii": ["Kisii Central", "Kisii East", "Kisii West", "Nyaribari Masaba", "Nyaribari Chache", "Bogonko", "Kitutu Chache"],
    "Migori": ["Migori", "Uriri", "Rongo", "Awendo"],
    "Homa Bay": ["Homa Bay Town", "Homa Bay East", "Homa Bay West", "Rangwe", "Ndhiwa", "Rachuonyo"],
    "Siaya": ["Siaya", "Bondo", "Rarieda", "Ugunja", "Ugenya", "Yala"],
    "Vihiga": ["Sabatia", "Hamisi", "Vihiga", "Emuhaya"],
    "Tharaka Nithi": ["Tharaka", "Meru South", "Chuka/Igambang'ombe", "Maara", "Mithare"],
    "Meru": ["Meru Central", "Imenti North", "Imenti South", "Buuri", "Igembe South", "Igembe North", "Igembe Central"],
    "Embu": ["Embu East", "Embu West", "Embu Central", "Mbeere North", "Mbeere South"],
    "Makueni": ["Makueni", "Kaiti", "Kibwezi West", "Kibwezi East", "Kilome"],
    "Kitui": ["Kitui Central", "Kitui East", "Kitui South", "Kitui West", "Mwingi North", "Mwingi Central", "Mwingi West"],
    "Mandera": ["Mandera West", "Mandera East", "Mandera Central", "Lamu East"],
    "Wajir": ["Wajir West", "Wajir East", "Wajir North", "Wajir South"],
    "Garissa": ["Garissa Township", "Garissa East", "Garissa South", "Ijara", "Balambala"],
    "Isiolo": ["Isiolo", "Merti", "Kinna"],
    "Marsabit": ["Marsabit Central", "Marsabit North", "Moyale"],
    "West Pokot": ["Kapenguria", "Kacheliba", "Pokot South", "Sigor"],
    "Kwale": ["Kwale", "Msambweni", "Lunga Lunga", "Matuga"],
    "Taita Taveta": ["Taita Taveta", "Wundanyi", "Mwatate", "Maktau"],
}
