# Generated by Django 5.2.8 on 2025-12-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trip_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='trips/'),
        ),
    ]
