# Generated by Django 5.2.8 on 2025-12-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_alter_galleryimage_options_comment_comment_image_and_more'),
        ('trips', '0012_rename_book_date_booking_created_at_and_more'),
    ]

    operations = [
    ]
